### ISSUE TITLE
계좌 조회 기능 구현에 대한 고민

### ISSUE THREAD

**Issue by ilgolf** [ilgolf/kotlinBank#30]
### 요구 사항

사용자가 홈 화면에서 자신의 갖고있는 계좌에 대한 정보를 간략하게 볼 수 있습니다. 해당 서비스에 필요한 정보는 다음과 같습니다. 

- 잔액
- 계좌 은행 (국민, 신한 등등 ...)
- 계좌 별칭

### 고민 Point

계좌 은행과 별칭은 memberId를 기준으로 List로 보여줍니다. 여기서 고민 point가 생겨납니다. 잔액 정보는 현재 외부 api 인 농협 api에 의존하고 있습니다. 외부 api에 완전한 의존은 예상치 못한 장애를 동반합니다. (예를 들어 우리만 요청을 보내고 있는 상황이 아니니 부하가 몰려 농협의 서비스가 장애가 나거나 해당 서버를 관리하다 예상치 못한 장애를 만나 서버에 문제가 생길 수 있습니다.)  이러한 이유로 외부 api는 철저히 주요 코어 비즈니스에는 영향을 줘선 안됩니다.

결국 최종적으로는 최대한 정확한 데이터를 클라이언트에게 보여주면서 외부 api 장애에 영향 받지 않는 비즈니스 로직을 구현하고 싶습니다. 

### 개발 방향성

- 조회 이벤트 발생 시 외부에서 데이터를 받아오되 Exception 발생 시 catch하여 조회 불가능 관련 메시지 or 레디스에 존재하는 마지막으로 조회 된  잔액을 보여줍니다. 

이외에 다른 의견 있으시면 코멘트 부탁드립니다.

**Comment by hubtwork** [comment]
#### 문제 상황 정리
- 외부 API 에 의한 계좌 정보 조회 서비스 구현
- 외부 API 에 의존해 계좌 잔액 정보 등을 Pull & Serve 해야하기 때문에 개발방향성에 대한 수립 필요
> 외부 의존성의 오류 등을 고려, 어떤 방식으로 데이터를 Serve 할 것인지에 따라 UX 가 상이하게 차이날 것으로 보임

#### 솔루션 분석
> *`B-API` - 이하 제안에선, 외부 은행 API 에 대해 B-API 로 칭함.*
- 제안하신 요구사항에 부합하는 현행 서비스들의 경우, 은행 혹은 핀테크 서비스 중 '마이데이터 - 잔액조회' 기능 카탈로그와 흡사함.
- 위 카탈로그의 경우, `개발 방향성`에서 말씀하신 부분을 1Step 구조가 아닌 이하 2Step 구조로 전달
> 언급하신 외부 API 에 대한 의존도 때문에 이를 캐시데이터를 이용해 전달하게 되는데, Front-Side 캐시와 Server-Side 캐시 형태, 두가지로 구분해볼 수 있는데 이를 위임하는 절차에 따라 다름.
- Front-Side 캐시의 경우, 접속한 모바일 기기 혹은 브라우저 등 클라이언트 매체에 따라 캐시 데이터의 최근 저장된 데이터 시점이 다르므로 멀티 플랫폼/디바이스 를 지원하고자 하는 서비스의 경우 적합하지 않음.
- **golf** 님의 경우 서버사이드 형태로 구현하는 것이 좋을 것으로 보이는데, 기존 방향성은 아래와 같은 문제를 수반할 수 있음.
> 클라이언트 요청에 따라 각 회원이 등록한 계좌 정보에 대해 개별 B-API 로부터 계좌 잔액정보 수집 및 내부 캐싱 및 반환
> 다만 이 케이스에서, 각 `B-API` 별 평균 트래블 타임 등이 다를 수 있으므로 ( 실제로는 예외가 발생하지 않고 내부적인 처리가 오래 걸려 응답이 늦게 도달하는 경우 등 ) 클라이언트에서는 트래블 타임이 긴 은행의 잔액정보 때문에 다른 정보의 도달 또한 늦어질 수 있음.

#### 제안 솔루션
- 위를 해결하기 위해 2Step 으로 API 구성을 분리
> (1) 가장 최근 성공한 해당 유저의 전체 보유계좌 잔액정보 조회 캐시 데이터 수취 API
> (2) 실제 각 연동 계좌에 대한 외부 API 호출해 캐시데이터 ( Redis , Memcached 등 이용 ) 동기화 및 반환하는 API
**이점** 
- 클라이언트는 위 2Step API 를 순차적으로 호출, 빠른 fetch 가 가능한 (1) API 를 통해 사용자에게 적은 커넥션 부하로 유의미한 데이터 수취 및 유저에게 디스플레이 가능 ( UX 용이성 ) - (2) API 의 통신 State 에 따라 추가 로딩 처리
- 이후 딜레이 혹은 예외가 생길수 있는 (2) API 를 통한 데이터 갱신 및 예외 상황 유저에게 전달 가능

**주의할점**
- 내부적으로 개인 계좌 잔액 정보를 들고 있어야하므로 암호화를 통한 데이터 관리
- API 호출에 대한 서버 부담을 줄이기 위해 커넥션 관리 및 페이로드 사이즈 리듀싱 전략 필요

**Comment by ilgolf** [comment]
## 계좌 정보 간략 조회

### 요구 사항

사용자가 홈 화면에서 자신의 갖고있는 계좌에 대한 정보를 간략하게 볼 수 있습니다. 해당 서비스에 필요한 정보는 다음과 같습니다.

- 잔액
- 계좌 은행 (국민, 신한 등등 ...)
- 계좌 별칭

### 초기 개발 방향성

- 잔액 조회는 오픈 api인 NH api에서 finAccount를 요청으로 보내 가져온다.
- 계좌 은행과 별칭은 MySQL DB에서 가져온다.
- 이 후 데이터를 합쳐 응답에 담아 반환한다.

### 외부 API 서버 장애 시 대처에 대한 방법

- 인터페이싱을 통해 장애 났을 때 빠르게 다른 동작을 하는 API를 `@Bean` 으로 바꾸어 처리하는 방법 (PASS)
    - 이 방법은 결국 장애가 났을 때 배포 프로세스를 거쳐야합니다. 이는 꽤나 번거로운 작업이 될 수 있습니다.
    - 비즈니스에 결국 완전한 영향을 없앤 것이 아닙니다. (Bean을 수동으로 계속해서 변경해주어야함)
- Message Broker를 이용하여 외부 api에 데이터를 가져옴 (고민 중…)
    - Message Queue를 컨트롤 하여 fail over에 대해 처리해줄 수 있고 현재 많은 기업에서 사용하고 있는 솔루션
    - 상당한 오버 엔지니어링 (인프라 추가 + fail over 등 너무 많은 작업이 소요)
    - Message Broker에 대한 현재 지식도 부족함
- 2step으로 구성을 분리하여 redis와 외부 api에서 데이터를 보여주는 방법(git Comment를 통해 배움)

- Server-side에서 캐시 형태로 저장하여 보관
- 1차로 캐시 데이터에서 조회하여 당장에 화면을 보여줌 (이 때 데이터 신뢰성은 좀 떨어짐 하지만 화면상 불편성 제거)
- 2차로 외부 연동된 API를 호출하여 실시간으로 데이터를 가져옴 이 때 가져왔을 때 Redis cache에 넣어주고 가져오지 못하면 에러 메시지를 내보내 현재 실시간 데이터가 아님을 사용자에게 전달
- 기본 응답 초기 값은 `???,???` 형태로 제공
- 이 후 데이터가 점차 쌓여가면 scale-out or scale-up 고려

- 동일한 요청이 가더라도 처리 시간에  따라 순서가 뒤집히거나 데이터 정합성 (처리 시간의 차이) 문제를 해결 어떻게 할 것인가?
    - 요청 타임스탬프를 기록했다가 타임스탬프를 이용해 filtering하는 방법을 사용
    - 농협에다가 요청을 날린 History 테이블을 추가하여 예상치 못한 장애에 대응할 수 있게 준비
